### ISSUE TITLE
compas_fab introduction TODO list

### ISSUE THREAD

**Issue by romanarust** [gramaziokohler/compas_fab#25]
- [x] rfab or robfab
- [x] Make graphic for coordinate frames
- [x] Make doc example for coordinate frames, add code (WIP)
- [x] Make doc example for creating robot model, update graphic of kinematic chain (WIP)
- [x] Robot graphic
- [ ] Robot doc example with code(WIP)
- [x] Robot.ghx (WIP RR)
- [x] Source colors and apply to robot (from urdf / mtl file)
- [x] Check why invalid mesh in GH
- [x] Add RobotMesh class to all CADs in compas?
- [ ] robot.setRCF(frame)
- [ ] robot.setTool(tool) (load tool from urdf)
- [x] Where to put ROS communication classes? (PoseStamped, JointState)
- [x] Use JointState or Configuration?
- [x] Remove unused folders / temp folders and temp files: e.g. datastructures, devices, ... or move into "develop"
- [x] Make graphic for node explanation
- [x] Make graphic for Action
- [x] Make graphic for Topic
- [x] Make graphic for Service
